require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

# Sinatra-specific configurations
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config.ru'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 100
